services:
  app:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - media_storage:/app/public/media
    post_start:
      - command: php artisan optimize
    restart: unless-stopped

  queue-worker:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    entrypoint: php artisan queue:work
    healthcheck:
      test: ["CMD", "bin/healthcheck-queue-worker"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env
    volumes:
      - media_storage:/app/public/media
    post_start:
      - command: php artisan optimize
    restart: unless-stopped

volumes:
  media_storage:
