services:
  app:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./public/media:/app/public/media
    post_start:
      - command: php artisan optimize

  scheduler:
    build:
      context: .
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
    entrypoint: php artisan schedule:work
    healthcheck:
      test: ["CMD", "bin/healthcheck-schedule"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env
    volumes:
      - ./public/media:/app/public/media
    post_start:
      - command: php artisan optimize
